"""Public Python API for hybrid electricity-system simulation."""

from energy_system_simulator.api import (
    build_model,
    ensure_writable_output_directory,
    load_data,
    load_model_config,
    run_simulation,
    solve,
    validate_data,
    validate_model_config,
)
from energy_system_simulator.config import ModelConfig, load_config
from energy_system_simulator.data_adapters import (
    DataProvenance,
    DataValidationReport,
    EuropeanDemandCsvAdapter,
    MissingDataPolicy,
    SnapshotResult,
    WeatherCsvAdapter,
    build_canonical_snapshot,
    run_data_preparation_spec,
    validate_canonical_frame,
)
from energy_system_simulator.exceptions import (
    ConfigurationError,
    DataValidationError,
    EnergySystemError,
    OptimisationError,
)
from energy_system_simulator.experiments import (
    ExperimentError,
    analyze_research_experiment,
    load_experiment_spec,
    reproduce_research_experiment,
    run_research_experiment,
    verify_experiment_manifest,
)
from energy_system_simulator.market import GeneratorSettlement, MarketAnalyzer, MarketSettlement
from energy_system_simulator.metadata import get_package_version
from energy_system_simulator.planning import (
    CapacityExpansionPlanner,
    CapacityExpansionProblem,
    CapacityExpansionResult,
    GenerationCandidate,
    InterconnectorCandidate,
    PlanningBlock,
    PlanningPolicy,
    StorageCandidate,
    TransmissionCandidate,
)
from energy_system_simulator.scenarios import (
    ScenarioDefinition,
    ScenarioExperiment,
    ScenarioExperimentError,
    ScenarioRunner,
    apply_overrides,
    finite_difference_sensitivity,
    run_experiment_file,
    stable_scenario_id,
)
from energy_system_simulator.simulation.engine import SimulationEngine, SimulationResult

__all__ = [
    "CapacityExpansionPlanner",
    "CapacityExpansionProblem",
    "CapacityExpansionResult",
    "ConfigurationError",
    "DataProvenance",
    "DataValidationError",
    "DataValidationReport",
    "EnergySystemError",
    "EuropeanDemandCsvAdapter",
    "ExperimentError",
    "GenerationCandidate",
    "GeneratorSettlement",
    "InterconnectorCandidate",
    "MarketAnalyzer",
    "MarketSettlement",
    "MissingDataPolicy",
    "ModelConfig",
    "OptimisationError",
    "PlanningBlock",
    "PlanningPolicy",
    "ScenarioDefinition",
    "ScenarioExperiment",
    "ScenarioExperimentError",
    "ScenarioRunner",
    "SimulationEngine",
    "SimulationResult",
    "SnapshotResult",
    "StorageCandidate",
    "TransmissionCandidate",
    "WeatherCsvAdapter",
    "analyze_research_experiment",
    "apply_overrides",
    "build_canonical_snapshot",
    "build_model",
    "ensure_writable_output_directory",
    "finite_difference_sensitivity",
    "load_config",
    "load_data",
    "load_experiment_spec",
    "load_model_config",
    "reproduce_research_experiment",
    "run_data_preparation_spec",
    "run_experiment_file",
    "run_research_experiment",
    "run_simulation",
    "solve",
    "stable_scenario_id",
    "validate_canonical_frame",
    "validate_data",
    "validate_model_config",
    "verify_experiment_manifest",
]
__version__ = get_package_version()
